language: python

notifications:
  email: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - DJANGO_VERSION=1.11.29
  - DJANGO_VERSION=2.2.19
  - DJANGO_VERSION=3.1.7

jobs:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=2.2.19
    - python: "2.7"
      env: DJANGO_VERSION=3.1.7
    - python: "3.4"
      env: DJANGO_VERSION=2.2.19
    - python: "3.4"
      env: DJANGO_VERSION=3.1.7
    - python: "3.5"
      env: DJANGO_VERSION=3.1.7

install:
  - pip install -q django==$DJANGO_VERSION

script:
  - python -B -tt -W ignore setup.py test
