language: python

notifications:
  email: false

env:
  - TOX_ENV=py27-1.11
  - TOX_ENV=py36-3.1
  - TOX_ENV=py37-3.1
  - TOX_ENV=py38-3.1
  - TOX_ENV=py39-3.1
  - TOX_ENV=pypy-3.1

install:
  - pip install --upgrade tox

script:
  - tox -e $TOX_ENV
